module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1370.84px",
        },
        colors: {
            transparent: "transparent",

            black: "#000",
            white: "#fff",
            red: {
                600: "#C51111",
            },
            grey: "#BEBEBE",
            accordionLine: "#CDCDCD",
            accordionText: "#4F4F4F",
        },
        spacing: {
            px: "1px",
            0: "0",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "1rem",
            5: "1.25rem",
            5.5: "1.5rem",
            6: "1.7rem",
            8: "2rem",
            9: "2.6rem",
            10: "2.8rem",
            12: "3rem",
            13: "3.05rem",
            14: "3.5rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            32: "8rem",
            33: "8.3rem",
            35: "8.7rem",
            40: "10rem",
            48: "11rem",
            50: "12.9rem",
            56: "14rem",
            58: "16rem",
            64: "17rem",
            65: "30.1rem",
            66: "20.75rem",
            67: "23.73rem",
            68: "25.34rem",
            78: "33rem",
            72: "41rem",
            88: "55rem",
        },
        backgroundColor: (theme) => theme("colors"),
        backgroundPosition: {
            bottom: "bottom",
            center: "center",
            left: "left",
            "left-bottom": "left bottom",
            "left-top": "left top",
            right: "right",
            "right-bottom": "right bottom",
            "right-top": "right top",
            top: "top",
        },
        backgroundSize: {
            auto: "auto",
            cover: "cover",
            contain: "contain",
            "70%": "70%",
        },
        borderColor: (theme) => ({
            ...theme("colors"),
            default: theme("colors.gray.300", "currentColor"),
        }),
        borderWidth: {
            default: "1px",
            0: "0",
            2: "2px",
            3: "3px",
            4: "4px",
            8: "8px",
        },
        container: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1300px",
        },
        cursor: {
            auto: "auto",
            default: "default",
            pointer: "pointer",
            wait: "wait",
            text: "text",
            move: "move",
            "not-allowed": "not-allowed",
        },
        fill: {
            current: "currentColor",
        },
        flex: {
            1: "1 1 0%",
            auto: "1 1 auto",
            initial: "0 1 auto",
            none: "none",
        },
        fontFamily: {
            robert: ["Roboto"],
            display: ["Oswald"],
        },
        fontSize: {
            xs: "0.75rem",
            xss: "0.85rem",
            sm: "0.93rem",
            base: "1.05rem",
            lg: "1.16rem",
            lgx: "1.3rem",
            xl: "1.4rem",
            "2xl": "1.5rem",
            "3xl": "1.75rem",
            "3.2xl": "2.1rem",
            "3.3xl": "2.32rem",
            "3.4xl": "2.45rem",
            "3.5xl": "2.6rem",
            "3.6xl": "2.8rem",
            "3.7xl": "3.05rem",
            "3.8xl": "3.25rem",
            "4xl": "3.5rem",
            "4.5xl": "3.65rem",
            "5xl": "4.7rem",
        },
        fontWeight: {
            hairline: "100",
            thin: "200",
            light: "300",
            normal: "400",
            medium: "500",
            semibold: "600",
            bold: "700",
            extrabold: "800",
            black: "900",
        },
        height: (theme) => ({
            auto: "auto",
            ...theme("spacing"),
            12: "3.17rem",
            full: "100%",
            screen: "100vh",
        }),
        lineHeight: {
            thin: "0.5",
            none: "1",
            tight: "1.25",
            snug: "1.375",
            normal: "1.5",
            relaxed: "1.625",
            loose: "2",
        },
        margin: (theme, { negative }) => ({
            auto: "auto",
            ...theme("spacing"),
            ...negative(theme("spacing")),
        }),
        maxHeight: {
            full: "100%",
            screen: "100vh",
        },
        maxWidth: {
            xs: "20rem",
            sm: "24rem",
            md: "28rem",
            lg: "32rem",
            xl: "36rem",
            "2xl": "42rem",
            "3xl": "48rem",
            "4xl": "56rem",
            "5xl": "64rem",
            "6xl": "72rem",
            full: "100%",
        },
        minHeight: {
            0: "0",
            full: "100%",
            screen: "100vh",
        },
        minWidth: {
            0: "0",
            full: "100%",
        },
        opacity: {
            0: "0",
            25: "0.25",
            50: "0.5",
            75: "0.75",
            90: "0.9",
            100: "1",
        },
        padding: (theme) => theme("spacing"),
        placeholderColor: (theme) => theme("colors"),
        stroke: {
            current: "currentColor",
        },
        textColor: (theme) => theme("colors"),
        width: (theme) => ({
            auto: "auto",
            ...theme("spacing"),
            "1/2": "50%",
            "1/3": "33.333333%",
            "2/3": "66.666667%",
            "1/4": "25%",
            "2/4": "50%",
            "3/4": "75%",
            "1/5": "20%",
            "2/5": "40%",
            "3/5": "60%",
            "4/5": "80%",
            "1/6": "16.666667%",
            "2/6": "33.333333%",
            "3/6": "50%",
            "4/6": "66.666667%",
            "5/6": "83.333333%",
            "1/12": "8.333333%",
            "2/12": "16.666667%",
            "3/12": "25%",
            "4/12": "30%",
            "5/12": "41.666667%",
            "6/12": "50%",
            "7/12": "58.333333%",
            "8/12": "66.666667%",
            "9/12": "75%",
            "10/12": "83.333333%",
            "11/12": "91.666667%",
            full: "100%",
            screen: "100vw",
        }),
        zIndex: {
            auto: "auto",
            0: "0",
            1: "1",
            10: "10",
            20: "20",
            30: "30",
            40: "40",
            50: "50",
        },
        extend: {
            animation: {
                slide: "slide 15s infinite",
            },
            keyframes: {
                slide: {
                    "0%": { top: "0" },
                    "4%": { top: "-4.7rem" },
                    "12.5%": { top: "-4.7rem" },
                    "16.5%": { top: "-9.4rem" },
                    "25%": { top: "-9.4rem" },
                    "29%": { top: "-14.1rem" },
                    "37.5%": { top: "-14.1rem" },
                    "41.5%": { top: "-18.8rem" },
                    "50%": { top: "-18.8rem" },
                    "54%": { top: "-23.5rem" },
                    "62.5%": { top: "-23.5rem" },
                    "66.5%": { top: "-28.2rem" },
                    "75%": { top: "-28.2rem" },
                    "79%": { top: "-32.9rem" },
                    "87.5%": { top: "-32.9rem" },
                    "91.5%": { top: "-37.6rem" },
                },
            },
        },
    },
    corePlugins: {},
    plugins: [],
};
